const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
require('dotenv').config();

const careerRoutes = require('./routes/careers');
const skillRoutes = require('./routes/skills');
const articleRoutes = require('./routes/articles');

const app = express();
const PORT = process.env.PORT || 5000;
const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/nextstep_nepal';

// Middleware
app.use(cors());
app.use(express.json());

// Routes
app.use('/api/careers', careerRoutes);
app.use('/api/skills', skillRoutes);
app.use('/api/articles', articleRoutes);

// Health check
app.get('/api/health', (req, res) => {
  res.json({ status: 'NextStep Nepal API is running 🚀' });
});

// Connect to MongoDB and start server
mongoose
  .connect(MONGO_URI)
  .then(async () => {
    console.log('✅ MongoDB connected');
    // Seed database with sample data on first run
    await seedDatabase();
    app.listen(PORT, () => console.log(`🚀 Server running on http://localhost:${PORT}`));
  })
  .catch((err) => {
    console.error('❌ MongoDB connection error:', err.message);
    console.log('💡 Starting server without DB for demo...');
    app.listen(PORT, () => console.log(`🚀 Server running on http://localhost:${PORT}`));
  });

// Seed sample data
async function seedDatabase() {
  const Career = require('./models/Career');
  const Skill = require('./models/Skill');
  const Article = require('./models/Article');

  const careerCount = await Career.countDocuments();
  if (careerCount > 0) {
    console.log('✅ Database already has data, skipping seed');
    return;
  }

  console.log('🌱 Seeding database with sample data...');

  await Career.insertMany([
    {
      _id: 'software-engineer',
      title: 'Software Engineer',
      description: 'Build digital products and solve complex problems through code. High demand in Nepal\'s growing IT sector. Work on everything from web apps to mobile applications.',
      category: 'Technology',
      icon: '💻',
      roadmap: [
        'Complete +2 Science (Physical Group recommended)',
        'Clear entrance exams (IOE/KU/PU) or join BIT program',
        'Earn Bachelor\'s Degree (BE Computer, BSc CSIT, or BIT)',
        'Build a GitHub portfolio with 3+ projects',
        'Apply for internships at tech companies',
        'Start as Junior Developer and grow to Senior/Lead',
      ],
      duration: '4 years (Bachelor\'s)',
      cost: 'NPR 300,000 – 1,500,000 (depending on college)',
      averageSalary: 'NPR 60,000 – 200,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Build and deploy real-world software applications',
        'Work at top tech companies in Nepal or globally',
        'Earn competitive salaries in USD while working remotely',
        'Start your own tech startup or SaaS product',
        'Specialize in AI, Cloud, Cybersecurity, or Mobile',
      ],
      benefits: [
        'High demand both in Nepal and globally',
        'Remote work opportunities from Nepal',
        'Continuous learning with new technologies',
        'Strong community support and resources',
        'Clear path to high-paying careers',
      ],
      institutes: [
        { name: 'IOE Pulchowk Campus', url: 'https://pcampus.edu.np' },
        { name: 'Kathmandu University (CS)', url: 'https://ku.edu.np' },
        { name: 'Herald International College', url: 'https://heraldcollege.edu.np' },
        { name: 'Softwarica College', url: 'https://softwarica.edu.np' },
      ],
      resources: [
        { name: 'freeCodeCamp', url: 'https://freecodecamp.org' },
        { name: 'The Odin Project', url: 'https://theodinproject.com' },
        { name: 'Coursera', url: 'https://coursera.org' },
      ],
    },
    {
      _id: 'ui-ux-designer',
      title: 'UI/UX Designer',
      description: 'Create intuitive and beautiful digital experiences. Bridge the gap between users and technology by designing user-centric interfaces for apps and websites.',
      category: 'Design',
      icon: '🎨',
      roadmap: [
        'Learn design principles (typography, color, layout)',
        'Master Figma or Adobe XD',
        'Study user research and psychology',
        'Build a portfolio with 3–5 case studies',
        'Apply for internships or freelance projects',
        'Grow to Senior Designer or Product Designer',
      ],
      duration: '1–2 years',
      cost: 'NPR 30,000 – 150,000',
      averageSalary: 'NPR 40,000 – 120,000/month',
      jobProspects: 'Very Good',
      achievements: [
        'Design user-friendly mobile apps and websites',
        'Conduct user research and usability testing',
        'Work as UI/UX Designer in tech startups',
        'Build a strong portfolio for global clients',
        'Lead design teams or start your own studio',
      ],
      benefits: [
        'Creative work with tangible outcomes',
        'High demand in tech startups',
        'Work collaboratively with developers',
        'Multiple industries to work in',
        'Strong community and design resources',
      ],
      institutes: [
        { name: 'Google UX Design Certificate', url: 'https://grow.google/certificates/ux-design/' },
        { name: 'Figma Learn', url: 'https://figma.com/resources/learn-design/' },
        { name: 'Arena Animation', url: 'https://www.arena-multimedia.com' },
        { name: 'Online: Interaction Design Foundation', url: 'https://www.interaction-design.org' },
      ],
      resources: [
        { name: 'Figma Learn', url: 'https://figma.com/resources/learn-design/' },
        { name: 'Google UX Design Certificate', url: 'https://grow.google/certificates/ux-design/' },
      ],
    },
    {
      _id: 'data-scientist',
      title: 'Data Scientist',
      description: 'Extract insights from data to drive business decisions. One of the fastest growing fields globally, working with AI, ML, and big data.',
      category: 'Technology',
      icon: '📊',
      roadmap: [
        'Complete +2 in Science or Management with Math',
        'Earn Bachelor\'s in CS, Statistics, or related field',
        'Learn Python and statistics fundamentals',
        'Master SQL, Pandas, and data visualization',
        'Study machine learning and AI basics',
        'Build a portfolio on Kaggle and apply for jobs',
      ],
      duration: '4–5 years',
      cost: 'NPR 300,000 – 1,200,000',
      averageSalary: 'NPR 70,000 – 200,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Analyze large datasets to extract business insights',
        'Build predictive models for real-world problems',
        'Work as Data Analyst, Data Scientist, or ML Engineer',
        'Create AI solutions for local Nepal markets',
        'Consult for international companies remotely',
      ],
      benefits: [
        'One of the highest-paying tech fields',
        'Growing demand across all industries',
        'Work on impactful, data-driven projects',
        'Options to work remotely for global companies',
        'Strong future growth potential with AI',
      ],
      institutes: [
        { name: 'Scaler Academy', url: 'https://www.scaler.com' },
        { name: 'DataCamp', url: 'https://www.datacamp.com' },
        { name: 'Coursera Data Science', url: 'https://www.coursera.org' },
        { name: 'Kaggle', url: 'https://kaggle.com' },
      ],
      resources: [
        { name: 'Kaggle Learn', url: 'https://kaggle.com/learn' },
        { name: 'fast.ai', url: 'https://fast.ai' },
      ],
    },
    {
      _id: 'civil-engineer',
      title: 'Civil Engineer',
      description: 'Design and build infrastructure that shapes Nepal\'s future — roads, bridges, buildings, and hydropower projects.',
      category: 'Engineering',
      icon: '🏗️',
      roadmap: [
        'Complete +2 Science with Mathematics',
        'Clear IOE entrance exam or apply to KU/PU',
        'Complete BE in Civil Engineering (4 years)',
        'Get licensed by Nepal Engineering Council',
        'Gain practical experience through internships',
        'Specialize or start your own consultancy',
      ],
      duration: '4–5 years (BE)',
      cost: 'NPR 400,000 – 1,500,000',
      averageSalary: 'NPR 40,000 – 150,000/month',
      jobProspects: 'Good',
      achievements: [
        'Design and supervise construction projects',
        'Work on Nepal\'s infrastructure development',
        'Specialize in structural, transportation, or water resources',
        'Start your own construction or consultancy firm',
        'Work internationally with PE certification',
      ],
      benefits: [
        'Essential for nation\'s development',
        'Stable career with consistent demand',
        'Opportunity to work on major projects',
        'Clear path to professional licensing',
        'Options for international work',
      ],
      institutes: [
        { name: 'IOE Pulchowk Campus', url: 'https://pcampus.edu.np' },
        { name: 'Kathmandu University', url: 'https://ku.edu.np' },
        { name: 'Pokhara University', url: 'https://pu.edu.np' },
        { name: 'Nepal Engineering Council', url: 'https://nec.gov.np' },
      ],
      resources: [
        { name: 'IOE Pulchowk Campus', url: 'https://pcampus.edu.np' },
        { name: 'Nepal Engineering Council', url: 'https://nec.gov.np' },
      ],
    },
    {
      _id: 'digital-marketer',
      title: 'Digital Marketer',
      description: 'Help businesses grow online through SEO, social media, content marketing, and data analytics. Essential for any modern business.',
      category: 'Business',
      icon: '📱',
      roadmap: [
        'Learn the fundamentals of digital marketing',
        'Master SEO basics and Google Ads',
        'Study social media marketing strategies',
        'Get certified (Google, Meta Blueprint)',
        'Build a portfolio with real projects',
        'Apply to agencies or freelance for clients',
      ],
      duration: '6 months – 2 years',
      cost: 'NPR 15,000 – 80,000',
      averageSalary: 'NPR 30,000 – 80,000/month',
      jobProspects: 'Good',
      achievements: [
        'Manage digital marketing campaigns for brands',
        'Increase website traffic and conversions',
        'Work as Digital Marketing Manager',
        'Start your own digital marketing agency',
        'Freelance for international clients',
      ],
      benefits: [
        'High demand as every business needs online presence',
        'Can start with minimal investment',
        'Work remotely and flexibly',
        'Clear metrics to measure success',
        'Multiple specialization paths',
      ],
      institutes: [
        { name: 'Google Digital Garage', url: 'https://learndigital.withgoogle.com' },
        { name: 'HubSpot Academy', url: 'https://academy.hubspot.com' },
        { name: 'Meta Blueprint', url: 'https://www.facebook.com/business/learn' },
        { name: 'Digital Nepal Academy', url: 'https://www.digitalnepal.com' },
      ],
      resources: [
        { name: 'Google Digital Garage', url: 'https://learndigital.withgoogle.com' },
        { name: 'HubSpot Academy', url: 'https://academy.hubspot.com' },
      ],
    },
    {
      _id: 'doctor',
      title: 'Doctor (MBBS)',
      description: 'Serve Nepal\'s healthcare needs and save lives. A highly respected profession with excellent career prospects in Nepal and abroad.',
      category: 'Healthcare',
      icon: '⚕️',
      roadmap: [
        'Complete +2 Science with Biology',
        'Score well in entrance exams (MECEE-BL)',
        'Complete 5.5-year MBBS program',
        'Complete 1-year mandatory internship',
        'Register with Nepal Medical Council',
        'Consider MD specialization or practice',
      ],
      duration: '6–10 years',
      cost: 'NPR 2,000,000 – 8,000,000 (private college)',
      averageSalary: 'NPR 80,000 – 300,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Diagnose and treat patients professionally',
        'Serve in hospitals across Nepal',
        'Specialize in surgery, medicine, or pediatrics',
        'Work internationally with proper certifications',
        'Contribute to Nepal\'s healthcare system',
      ],
      benefits: [
        'Highly respected profession',
        'Excellent salary potential',
        'Job security and demand',
        'Opportunity to help others',
        'Options to work globally',
      ],
      institutes: [
        { name: 'Tribhuvan University IOM', url: 'https://iom.edu.np' },
        { name: 'B.P. Koirala Institute', url: 'https://bpkohs.edu.np' },
        { name: 'Kathmandu Medical College', url: 'https://kmc.edu.np' },
        { name: 'Nepal Medical Council', url: 'https://nmc.org.np' },
      ],
      resources: [
        { name: 'Nepal Medical Council', url: 'https://nmc.org.np' },
        { name: 'Tribhuvan University IOM', url: 'https://iom.edu.np' },
      ],
    },
    {
      _id: 'chartered-accountant',
      title: 'Chartered Accountant (CA)',
      description: 'Expert in accounting, auditing, and taxation. High demand in Nepal\'s corporate sector, banks, and financial institutions.',
      category: 'Business',
      icon: '📑',
      roadmap: [
        'Complete +2 in Commerce or Management',
        'Join ICAN for CA program',
        'Clear CA Foundation and Intermediate exams',
        'Complete 3 years of practical training',
        'Clear CA Final examination',
        'Register and practice as CA',
      ],
      duration: '5–7 years',
      cost: 'NPR 500,000 – 1,500,000',
      averageSalary: 'NPR 60,000 – 200,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Audit financial statements of companies',
        'Work in banks, corporations, or government',
        'Provide tax advisory services',
        'Start your own accounting firm',
        'Work internationally with CA equivalency',
      ],
      benefits: [
        'High salary and prestige',
        'Job security in finance sector',
        'Multiple career paths',
        'Opportunity to start own practice',
        'Respected professional qualification',
      ],
      institutes: [
        { name: 'ICAN (Institute of Chartered Accountants)', url: 'https://www.ican.org.np' },
        { name: 'CT Foundation', url: 'https://www.ctfoundation.edu.np' },
        { name: 'SAICA (South Africa)', url: 'https://www.saica.co.za' },
        { name: 'Online: AICPA', url: 'https://www.aicpa.org' },
      ],
      resources: [
        { name: 'ICAN Nepal', url: 'https://www.ican.org.np' },
        { name: 'CA Club Nepal', url: 'https://www.caclubnepal.com' },
      ],
    },
    {
      _id: 'nurse',
      title: 'Registered Nurse',
      description: 'Provide essential healthcare services in hospitals, clinics, and community settings. High demand globally for qualified nurses.',
      category: 'Healthcare',
      icon: '🏥',
      roadmap: [
        'Complete +2 Science with Biology',
        'Join BSc Nursing or PCL Nursing program',
        'Complete clinical training and internships',
        'Register with Nepal Nursing Council',
        'Work in hospitals or healthcare facilities',
        'Consider specialization or abroad opportunities',
      ],
      duration: '3–4 years',
      cost: 'NPR 300,000 – 1,000,000',
      averageSalary: 'NPR 35,000 – 100,000/month',
      jobProspects: 'Very Good',
      achievements: [
        'Provide quality patient care in hospitals',
        'Specialize in ICU, ER, or pediatric nursing',
        'Work in healthcare facilities across Nepal',
        'Opportunity to work abroad (USA, UK, Australia)',
        'Pursue advanced nursing degrees',
      ],
      benefits: [
        'High demand globally',
        'Noble profession helping others',
        'Job security in healthcare',
        'Clear path to working abroad',
        'Multiple specialization options',
      ],
      institutes: [
        { name: 'TU Nursing Campus', url: 'https://www.iom.edu.np' },
        { name: 'B.P. Koirala Institute (Nursing)', url: 'https://bpkohs.edu.np' },
        { name: 'Nepal Nursing Council', url: 'https://nnc.org.np' },
        { name: 'Online: Prometric for abroad', url: 'https://www.prometric.com' },
      ],
      resources: [
        { name: 'Nepal Nursing Council', url: 'https://nnc.org.np' },
        { name: 'WHO Nursing Resources', url: 'https://www.who.int' },
      ],
    },
    {
      _id: 'architect',
      title: 'Architect',
      description: 'Design buildings and spaces that shape Nepal\'s skylines. Combine creativity with technical skills to create functional and beautiful structures.',
      category: 'Engineering',
      icon: '🏛️',
      roadmap: [
        'Complete +2 Science with Mathematics',
        'Join Bachelor of Architecture (B.Arch) program',
        'Complete 5-year architecture degree',
        'Gain practical experience through internships',
        'Register with Nepal Architects Association',
        'Build a portfolio of design projects',
      ],
      duration: '5 years',
      cost: 'NPR 500,000 – 2,000,000',
      averageSalary: 'NPR 50,000 – 150,000/month',
      jobProspects: 'Good',
      achievements: [
        'Design residential and commercial buildings',
        'Work on heritage conservation projects',
        'Specialize in sustainable or urban design',
        'Start your own architecture firm',
        'Work on international projects',
      ],
      benefits: [
        'Creative and fulfilling work',
        'Shape how cities look and feel',
        'Combine art and engineering',
        'High-profile project opportunities',
        'Options for entrepreneurship',
      ],
      institutes: [
        { name: 'Institute of Engineering (IOE)', url: 'https://pcampus.edu.np' },
        { name: 'Kathmandu University', url: 'https://ku.edu.np' },
        { name: 'Nepal Architects Association', url: 'https://www.naa.org.np' },
        { name: 'School of Architecture (SoA)', url: 'https://soa.edu.np' },
      ],
      resources: [
        { name: 'Autodesk Revit', url: 'https://www.autodesk.com' },
        { name: 'ArchDaily', url: 'https://www.archdaily.com' },
      ],
    },
    {
      _id: 'lawyer',
      title: 'Lawyer / Advocate',
      description: 'Practice law and fight for justice. High-demand profession in Nepal\'s growing legal and corporate sectors.',
      category: 'Law',
      icon: '⚖️',
      roadmap: [
        'Complete +2 in any stream',
        'Join Bachelor of Law (LLB) program (3 years)',
        'Clear Nepal Bar Council exam',
        'Complete 1-year bar practicum',
        'Register as Advocate with Bar Council',
        'Specialize in corporate, criminal, or civil law',
      ],
      duration: '4–6 years',
      cost: 'NPR 200,000 – 1,000,000',
      averageSalary: 'NPR 40,000 – 200,000/month',
      jobProspects: 'Very Good',
      achievements: [
        'Practice in courts across Nepal',
        'Work as corporate legal advisor',
        'Specialize in constitutional or human rights law',
        'Start your own law firm',
        'Work internationally with foreign bar membership',
      ],
      benefits: [
        'Highly respected profession',
        'Multiple specialization options',
        'Clear career progression',
        'Opportunity to make a difference',
        'High earning potential in corporate law',
      ],
      institutes: [
        { name: 'Tribhuvan University (Faculty of Law)', url: 'https://tu.edu.np' },
        { name: 'Nepal Law Campus', url: 'https://nlcm.edu.np' },
        { name: 'Nepal Bar Council', url: 'https://www.lawcouncil.gov.np' },
        { name: ' Kathmandu University School of Law', url: 'https://ku.edu.np' },
      ],
      resources: [
        { name: 'Nepal Law Commission', url: 'https://lawcommission.gov.np' },
        { name: 'Supreme Court of Nepal', url: 'https://supremecourt.gov.np' },
      ],
    },
    {
      _id: 'pharmacist',
      title: 'Pharmacist',
      description: 'Dispense medicines and provide healthcare advice. Essential profession in healthcare with growing demand in Nepal.',
      category: 'Healthcare',
      icon: '💊',
      roadmap: [
        'Complete +2 Science with Biology',
        'Join Bachelor of Pharmacy (B.Pharm) program',
        'Complete 4-year pharmacy degree',
        'Register with Nepal Pharmacy Council',
        'Work in hospitals, pharmacies, or pharma companies',
        'Consider specialization or higher studies',
      ],
      duration: '4 years',
      cost: 'NPR 400,000 – 1,500,000',
      averageSalary: 'NPR 30,000 – 80,000/month',
      jobProspects: 'Good',
      achievements: [
        'Dispense medications safely and accurately',
        'Provide patient counseling on drug usage',
        'Work in pharmaceutical companies',
        'Specialize in clinical pharmacy or research',
        'Start your own pharmacy business',
      ],
      benefits: [
        'Growing healthcare sector',
        'Job stability and security',
        'Work in various healthcare settings',
        'Entrepreneurship opportunities',
        'Potential for higher studies abroad',
      ],
      institutes: [
        { name: 'Kathmandu University (Pharmacy)', url: 'https://ku.edu.np' },
        { name: 'Tribhuvan University (IOM)', url: 'https://iom.edu.np' },
        { name: 'Nepal Pharmacy Council', url: 'https://www.npc.gov.np' },
        { name: 'B.P. Koirala Institute', url: 'https://bpkohs.edu.np' },
      ],
      resources: [
        { name: 'Nepal Pharmacy Council', url: 'https://www.npc.gov.np' },
        { name: 'WHO Medicines', url: 'https://www.who.int/topics/medicines' },
      ],
    },
    {
      _id: 'pilot',
      title: 'Commercial Pilot',
      description: 'Fly aircraft and build a career in aviation. High-paying career for those who dream of the skies.',
      category: 'Aviation',
      icon: '✈️',
      roadmap: [
        'Complete +2 in any stream with Physics and Math',
        'Obtain Class 2 Medical Certificate',
        'Join Flight Training School (in Nepal or abroad)',
        'Earn Private Pilot License (PPL)',
        'Earn Commercial Pilot License (CPL)',
        'Build hours and get type rating for airlines',
      ],
      duration: '2–3 years (training)',
      cost: 'NPR 3,000,000 – 10,000,000 (full training)',
      averageSalary: 'NPR 150,000 – 500,000/month',
      jobProspects: 'Good',
      achievements: [
        'Fly commercial aircraft for airlines',
        'Work as flight instructor',
        'Build hours for captain promotion',
        'Specialize in cargo or helicopter operations',
        'Work for international airlines',
      ],
      benefits: [
        'High salary and prestigious career',
        'Travel the world',
        'Job security in growing aviation sector',
        'Clear advancement path to captain',
        'Adventure and excitement',
      ],
      institutes: [
        { name: 'Koshi Aviation', url: 'https://www.koshihelicopter.com' },
        { name: 'Buddha Air Training', url: 'https://www.buddhaair.com' },
        { name: 'FAA (USA)', url: 'https://www.faa.gov' },
        { name: 'CAE Oxford Aviation Academy', url: 'https://www.cae.com' },
      ],
      resources: [
        { name: 'Civil Aviation Authority Nepal', url: 'https://www.caa.gov.np' },
        { name: 'FAA Training', url: 'https://www.faa.gov/pilots' },
      ],
    },
    {
      _id: 'journalist',
      title: 'Journalist / Media Professional',
      description: 'Report news and tell stories that matter. Essential for democracy and keeping the public informed in Nepal.',
      category: 'Media',
      icon: '📰',
      roadmap: [
        'Complete +2 in any stream',
        'Join Bachelor of Journalism & Mass Communication',
        'Build portfolio with published articles',
        'Intern at newspapers, TV, or online media',
        'Start as Reporter and grow to Editor',
        'Specialize in investigative or digital journalism',
      ],
      duration: '4 years',
      cost: 'NPR 200,000 – 800,000',
      averageSalary: 'NPR 25,000 – 80,000/month',
      jobProspects: 'Good',
      achievements: [
        'Report breaking news stories',
        'Conduct investigative journalism',
        'Work as Editor or News Anchor',
        'Build a career in digital media',
        'Win journalism awards',
      ],
      benefits: [
        'Make a real impact on society',
        'Tell important stories',
        'Work in dynamic, fast-paced environment',
        'Multiple media platforms to work in',
        'Opportunity for recognition',
      ],
      institutes: [
        { name: 'Tribhuvan University (Journalism)', url: 'https://tu.edu.np' },
        { name: 'Kathmandu University (Media)', url: 'https://ku.edu.np' },
        { name: 'Press Council Nepal', url: 'https://www.presscouncilnepal.gov.np' },
        { name: 'NEFEJ', url: 'http://www.nefej.org' },
      ],
      resources: [
        { name: 'Reuters Journalism', url: 'https://www.reuters.com/journalists' },
        { name: 'Columbia Journalism Review', url: 'https://www.cjr.org' },
      ],
    },
    {
      _id: 'teacher',
      title: 'Teacher / Educator',
      description: 'Shape young minds and build Nepal\'s future. From primary school to university professor.',
      category: 'Education',
      icon: '📚',
      roadmap: [
        'Complete +2 in any stream',
        'Join Bachelor of Education (B.Ed) or B.El.Ed',
        'Complete 4-year teacher training',
        'Clear Teacher Service Commission exam',
        'Get posted in government or private schools',
        'Pursue M.Ed for career advancement',
      ],
      duration: '4 years',
      cost: 'NPR 150,000 – 600,000',
      averageSalary: 'NPR 25,000 – 80,000/month',
      jobProspects: 'Good',
      achievements: [
        'Teach and inspire students',
        'Become Head Teacher or Principal',
        'Develop curriculum and educational materials',
        'Work in teacher training or education policy',
        'Start your own coaching center or school',
      ],
      benefits: [
        'Noble profession shaping future',
        'Job security with government jobs',
        'Long holidays and work-life balance',
        'Multiple specialization options',
        'Opportunity to make a difference',
      ],
      institutes: [
        { name: 'TU Faculty of Education', url: 'https://tu.edu.np' },
        { name: 'Himalayan Whitehouse College', url: 'https://hwc.edu.np' },
        { name: 'NCT', url: 'https://nct.gov.np' },
        { name: 'Online: Teaching Courses', url: 'https://www.coursera.org' },
      ],
      resources: [
        { name: 'Ministry of Education Nepal', url: 'https://moe.gov.np' },
        { name: 'CDC Nepal', url: 'https://www.cdc.gov.np' },
      ],
    },
    {
      _id: 'electrician',
      title: 'Electrician / Electrical Technician',
      description: 'Install and maintain electrical systems. Essential trade with steady demand in construction and industry.',
      category: 'Technical',
      icon: '⚡',
      roadmap: [
        'Complete +2 in Science or Technical stream',
        'Join ITI or CTEVT electrician program',
        'Complete 1–3 year vocational training',
        'Pass licensing exam for electrical work',
        'Work in construction, industry, or start business',
        'Specialize in solar, industrial, or power systems',
      ],
      duration: '1–3 years',
      cost: 'NPR 20,000 – 150,000',
      averageSalary: 'NPR 25,000 – 70,000/month',
      jobProspects: 'Good',
      achievements: [
        'Install electrical systems in buildings',
        'Maintain industrial electrical equipment',
        'Specialize in renewable energy (solar)',
        'Start your own electrical business',
        'Work internationally as skilled electrician',
      ],
      benefits: [
        'Always in demand trade',
        'Practical skills with immediate employment',
        'Multiple work settings',
        'Entrepreneurship opportunities',
        'Potential for international work',
      ],
      institutes: [
        { name: 'CTEVT', url: 'https://www.ctevt.org.np' },
        { name: 'Pashupati TMCT', url: 'https://pashupatitmct.edu.np' },
        { name: 'NEFEJ Technical Institute', url: 'http://www.nefej.org' },
        { name: 'Online: Electrical Training', url: 'https://www.coursera.org' },
      ],
      resources: [
        { name: 'Nepal Electrical Authority', url: 'https://www.nea.org.np' },
        { name: 'CTEVT', url: 'https://www.ctevt.org.np' },
      ],
    },
    {
      _id: 'hotel-management',
      title: 'Hotel Management Professional',
      description: 'Manage hotels, restaurants, and tourism services. Nepal\'s tourism sector offers exciting career opportunities.',
      category: 'Hospitality',
      icon: '🏨',
      roadmap: [
        'Complete +2 in any stream',
        'Join Bachelor in Hotel Management (BHM)',
        'Complete 4-year program',
        'Gain experience through internships',
        'Start in entry-level positions and grow',
        'Specialize in hospitality, events, or food & beverage',
      ],
      duration: '4 years',
      cost: 'NPR 300,000 – 1,200,000',
      averageSalary: 'NPR 25,000 – 80,000/month',
      jobProspects: 'Good',
      achievements: [
        'Manage hotel operations',
        'Work as Restaurant Manager or Chef',
        'Specialize in event management',
        'Work in luxury resorts or cruise ships',
        'Start your own restaurant or hospitality business',
      ],
      benefits: [
        'Dynamic and exciting industry',
        'Work in beautiful locations',
        'Career advancement opportunities',
        'International work possibilities',
        'Entrepreneurship options',
      ],
      institutes: [
        { name: 'Kathmandu University (Hospitality)', url: 'https://ku.edu.np' },
        { name: 'NATHM', url: 'https://www.nathm.edu.np' },
        { name: 'KIM Hospitality', url: 'https://www.kim.edu.np' },
        { name: 'Swiss Education Group', url: 'https://www.swisseducation.com' },
      ],
      resources: [
        { name: 'Nepal Tourism Board', url: 'https://www.welcomenepal.com' },
        { name: 'Ministry of Tourism', url: 'https://www.tourism.gov.np' },
      ],
    },
    {
      _id: 'banker',
      title: 'Banker / Finance Professional',
      description: 'Work in banking, insurance, and financial services. The backbone of Nepal\'s economy.',
      category: 'Finance',
      icon: '🏦',
      roadmap: [
        'Complete +2 in Commerce or Management',
        'Join BBA, BBS, or BCom program',
        'Clear bank entrance exams',
        'Join as Officer or Management Trainee',
        'Clear competitive exams for promotion',
        'Specialize in credit, treasury, or digital banking',
      ],
      duration: '4 years',
      cost: 'NPR 200,000 – 1,000,000',
      averageSalary: 'NPR 35,000 – 150,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Manage bank operations and customer accounts',
        'Work in credit, loans, or treasury',
        'Become Branch Manager or above',
        'Work in NRB or regulatory bodies',
        'Transition to corporate finance or investment',
      ],
      benefits: [
        'Job security in growing banking sector',
        'Competitive salary and benefits',
        'Clear promotion path',
        'Work in reputable institutions',
        'Opportunity to specialize',
      ],
      institutes: [
        { name: 'Tribhuvan University (BBA/BBS)', url: 'https://tu.edu.np' },
        { name: 'NIBM', url: 'https://www.nibm.edu.np' },
        { name: 'Nepal Rastra Bank', url: 'https://www.nrb.org.np' },
        { name: 'Patan College for Business', url: 'https://pcbs.edu.np' },
      ],
      resources: [
        { name: 'Nepal Rastra Bank', url: 'https://www.nrb.org.np' },
        { name: 'Nepal Bankers Association', url: 'https://www.nepalbankers.com' },
      ],
    },
    {
      _id: 'agriculture',
      title: 'Agriculture Officer / Agri-Scientist',
      description: 'Work in farming, food production, and agricultural development. Transform Nepal\'s agriculture sector.',
      category: 'Agriculture',
      icon: '🌾',
      roadmap: [
        'Complete +2 Science with Biology',
        'Join Bachelor in Agriculture (B.Sc Ag) or B.V.Sc',
        'Complete 4-year agriculture degree',
        'Clear AFO (Agriculture Field Officer) exam',
        'Work in government, NGOs, or agribusiness',
        'Specialize in horticulture, livestock, or research',
      ],
      duration: '4 years',
      cost: 'NPR 200,000 – 800,000',
      averageSalary: 'NPR 30,000 – 80,000/month',
      jobProspects: 'Good',
      achievements: [
        'Improve farming techniques and yields',
        'Work as Agriculture Extension Officer',
        'Develop sustainable farming practices',
        'Start agri-business or consultancy',
        'Work in food processing or exports',
      ],
      benefits: [
        'Contribute to food security',
        'Work outdoors and with communities',
        'Government job opportunities',
        'Growing agribusiness sector',
        'Entrepreneurship in agriculture',
      ],
      institutes: [
        { name: 'IAAS (TU)', url: 'https://iaas.edu.np' },
        { name: 'AFU', url: 'https://www.afu.edu.np' },
        { name: 'Karnali Agriculture College', url: 'https://kac.edu.np' },
        { name: 'Nepal Agricultural Research Council', url: 'https://www.narc.gov.np' },
      ],
      resources: [
        { name: 'Ministry of Agriculture', url: 'https://www.moald.gov.np' },
        { name: 'FAO Nepal', url: 'https://www.fao.org/nepal' },
      ],
    },
    {
      _id: 'cybersecurity',
      title: 'Cybersecurity Expert',
      description: 'Protect computer systems and networks from cyber attacks. One of the most critical and high-paying fields in technology.',
      category: 'Technology',
      icon: '🔒',
      roadmap: [
        'Complete +2 Science with Mathematics',
        'Earn Bachelor in Computer Science or IT',
        'Learn networking, OS, and security fundamentals',
        'Get certified (CompTIA Security+, CEH)',
        'Gain experience in security operations',
        'Specialize in ethical hacking or security analysis',
      ],
      duration: '4 years',
      cost: 'NPR 300,000 – 1,500,000',
      averageSalary: 'NPR 80,000 – 200,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Protect organizations from cyber attacks',
        'Conduct penetration testing',
        'Implement security policies and procedures',
        'Work as CISO or Security Architect',
        'Consult for government and corporations',
      ],
      benefits: [
        'Critical and in-demand field',
        'High salary worldwide',
        'Work remotely for global companies',
        'Constantly evolving and challenging',
        'Contribute to national security',
      ],
      institutes: [
        { name: 'IOE Pulchowk Campus', url: 'https://pcampus.edu.np' },
        { name: 'Kathmandu University', url: 'https://ku.edu.np' },
        { name: 'Online: CompTIA', url: 'https://www.comptia.org' },
        { name: 'EC-Council (CEH)', url: 'https://www.eccouncil.org' },
      ],
      resources: [
        { name: 'Cybrary', url: 'https://www.cybrary.it' },
        { name: 'OWASP', url: 'https://owasp.org' },
      ],
    },
    {
      _id: 'game-developer',
      title: 'Game Developer',
      description: 'Create video games and interactive experiences. Combine programming with creativity to build immersive games.',
      category: 'Technology',
      icon: '🎮',
      roadmap: [
        'Learn programming basics (C++, C#, or Unity)',
        'Study game design principles',
        'Master Unity or Unreal Engine',
        'Build a portfolio of game projects',
        'Join game studios or freelance',
        'Specialize in graphics, AI, or game design',
      ],
      duration: '2–4 years',
      cost: 'NPR 50,000 – 300,000',
      averageSalary: 'NPR 50,000 – 150,000/month',
      jobProspects: 'Good',
      achievements: [
        'Develop and publish video games',
        'Work at gaming studios',
        'Create VR/AR experiences',
        'Freelance as indie game developer',
        'Build your own game studio',
      ],
      benefits: [
        'Turn passion into career',
        'Creative and fun work',
        'Growing gaming industry',
        'Remote work opportunities',
        'Potential for hit games and fame',
      ],
      institutes: [
        { name: 'Leapfrog Technology Academy', url: 'https://www.lftechnology.com' },
        { name: 'Online: Unity Learn', url: 'https://learn.unity.com' },
        { name: 'Online: Unreal Academy', url: 'https://www.unrealengine.com' },
        { name: 'GameDev.tv', url: 'https://www.gamedev.tv' },
      ],
      resources: [
        { name: 'Unity Learn', url: 'https://learn.unity.com' },
        { name: 'Brackeys (YouTube)', url: 'https://www.youtube.com/brackeys' },
      ],
    },
    {
      _id: 'devops-engineer',
      title: 'DevOps Engineer',
      description: 'Bridge development and operations to streamline software delivery. Essential for modern tech companies.',
      category: 'Technology',
      icon: '🔧',
      roadmap: [
        'Learn Linux, networking, and scripting',
        'Master Git and version control',
        'Learn CI/CD pipelines (Jenkins, GitLab)',
        'Study Docker and Kubernetes',
        'Learn cloud platforms (AWS, GCP)',
        'Implement infrastructure as code',
      ],
      duration: '2–3 years',
      cost: 'NPR 50,000 – 200,000',
      averageSalary: 'NPR 80,000 – 180,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Automate software deployment',
        'Manage cloud infrastructure',
        'Implement CI/CD pipelines',
        'Improve system reliability',
        'Work as SRE or Platform Engineer',
      ],
      benefits: [
        'High demand in tech companies',
        'Excellent salary',
        'Work with cutting-edge tools',
        'Remote work opportunities',
        'Key role in modern development',
      ],
      institutes: [
        { name: 'AWS Training', url: 'https://aws.amazon.com/training' },
        { name: 'Google Cloud Training', url: 'https://cloud.google.com/training' },
        { name: 'Linux Foundation', url: 'https://www.linuxfoundation.org' },
        { name: 'Online: Udemy DevOps', url: 'https://www.udemy.com' },
      ],
      resources: [
        { name: 'Docker Docs', url: 'https://docs.docker.com' },
        { name: 'Kubernetes Docs', url: 'https://kubernetes.io/docs' },
      ],
    },
    {
      _id: 'project-manager',
      title: 'Project Manager',
      description: 'Lead teams and manage projects from start to finish. Essential for delivering products on time and within budget.',
      category: 'Business',
      icon: '📋',
      roadmap: [
        'Complete Bachelor in any field',
        'Learn project management methodologies (Agile, Scrum)',
        'Get PMP or Prince2 certified',
        'Start managing small projects',
        'Build experience with larger projects',
        'Advance to program or portfolio management',
      ],
      duration: '4 years + experience',
      cost: 'NPR 50,000 – 200,000 (certifications)',
      averageSalary: 'NPR 60,000 – 200,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Lead successful project deliveries',
        'Manage cross-functional teams',
        'Implement project management tools',
        'Become Program Manager or CTO',
        'Consult or start your own firm',
      ],
      benefits: [
        'High demand across all industries',
        'Leadership and strategic role',
        'Competitive salary',
        'Work in diverse sectors',
        'Clear path to executive roles',
      ],
      institutes: [
        { name: 'PMI Nepal', url: 'https://www.pmi.org' },
        { name: 'Scrum Alliance', url: 'https://www.scrumalliance.org' },
        { name: 'PRINCE2', url: 'https://www.axelos.com' },
        { name: 'Online: Coursera PM', url: 'https://www.coursera.org' },
      ],
      resources: [
        { name: 'PMI', url: 'https://www.pmi.org' },
        { name: 'Atlassian (Jira)', url: 'https://www.atlassian.com/software/jira' },
      ],
    },
    {
      _id: 'psychologist',
      title: 'Psychologist',
      description: 'Study human behavior and mental processes. Help people overcome psychological challenges and improve well-being.',
      category: 'Healthcare',
      icon: '🧠',
      roadmap: [
        'Complete +2 in any stream',
        'Earn Bachelor in Psychology (BA/BSc)',
        'Complete Master in Psychology (MA/MSc)',
        'Gain clinical experience and supervision',
        'Register with Nepal Health Professional Council',
        'Specialize in clinical, counseling, or organizational psychology',
      ],
      duration: '5–6 years',
      cost: 'NPR 300,000 – 1,500,000',
      averageSalary: 'NPR 40,000 – 100,000/month',
      jobProspects: 'Good',
      achievements: [
        'Diagnose and treat mental health conditions',
        'Conduct therapy and counseling',
        'Work in corporate or organizational settings',
        'Conduct research in psychology',
        'Specialize in child, sports, or clinical psychology',
      ],
      benefits: [
        'Make a real difference in lives',
        'Growing mental health awareness',
        'Diverse career paths',
        'Work in various settings',
        'Continuous learning and growth',
      ],
      institutes: [
        { name: 'Tribhuvan University (Psychology)', url: 'https://tu.edu.np' },
        { name: 'Kathmandu University', url: 'https://ku.edu.np' },
        { name: 'TU Faculty of Humanities', url: 'https://tu.edu.np' },
        { name: 'Online: APA', url: 'https://www.apa.org' },
      ],
      resources: [
        { name: 'American Psychological Association', url: 'https://www.apa.org' },
        { name: 'Psychology Today', url: 'https://www.psychologytoday.com' },
      ],
    },
    {
      _id: 'dentist',
      title: 'Dentist',
      description: 'Provide oral healthcare and dental treatments. Essential medical profession with growing demand.',
      category: 'Healthcare',
      icon: '🦷',
      roadmap: [
        'Complete +2 Science with Biology',
        'Clear dental entrance exam',
        'Complete BDS (Bachelor of Dental Surgery) 4 years',
        'Complete 1-year internship',
        'Register with Nepal Dental Association',
        'Practice or specialize (MDS)',
      ],
      duration: '5–6 years',
      cost: 'NPR 2,000,000 – 6,000,000',
      averageSalary: 'NPR 60,000 – 200,000/month',
      jobProspects: 'Very Good',
      achievements: [
        'Diagnose and treat dental problems',
        'Perform dental surgeries and procedures',
        'Specialize in orthodontics or oral surgery',
        'Run your own dental clinic',
        'Work in hospitals or dental chains',
      ],
      benefits: [
        'High-earning profession',
        'Growing demand for dental care',
        'Work independently or in hospitals',
        'Specialization opportunities',
        'Entrepreneurship potential',
      ],
      institutes: [
        { name: 'B.P. Koirala Institute (Dental)', url: 'https://bpkohs.edu.np' },
        { name: 'Kathmandu Medical College', url: 'https://kmc.edu.np' },
        { name: 'Nobel Medical College', url: 'https://www.nobelmedical.edu.np' },
        { name: 'Nepal Dental Association', url: 'https://nda.org.np' },
      ],
      resources: [
        { name: 'Nepal Dental Association', url: 'https://nda.org.np' },
        { name: 'American Dental Association', url: 'https://www.ada.org' },
      ],
    },
    {
      _id: 'social-worker',
      title: 'Social Worker',
      description: 'Help individuals and communities overcome challenges. Make a real difference in society.',
      category: 'Social',
      icon: '🤝',
      roadmap: [
        'Complete +2 in any stream',
        'Earn Bachelor in Social Work (BSW)',
        'Gain practical experience through internships',
        'Complete Master in Social Work (MSW) for advancement',
        'Work with NGOs, government, or social enterprises',
        'Specialize in child welfare, mental health, or community development',
      ],
      duration: '4–6 years',
      cost: 'NPR 150,000 – 600,000',
      averageSalary: 'NPR 25,000 – 70,000/month',
      jobProspects: 'Good',
      achievements: [
        'Support vulnerable populations',
        'Work in child welfare or mental health',
        'Lead community development projects',
        'Advocate for social justice',
        'Work with international NGOs',
      ],
      benefits: [
        'Make meaningful impact',
        'Work in diverse settings',
        'Growing NGO sector in Nepal',
        'Opportunities abroad',
        'Noble and fulfilling work',
      ],
      institutes: [
        { name: 'Tribhuvan University (Social Work)', url: 'https://tu.edu.np' },
        { name: 'Kathmandu University', url: 'https://ku.edu.np' },
        { name: 'Martin Chautari', url: 'https://www.martinchautari.org.np' },
        { name: 'Online: CSWE', url: 'https://www.cswe.org' },
      ],
      resources: [
        { name: 'NASW', url: 'https://www.socialworkers.org' },
        { name: 'UNDP Nepal', url: 'https://www.undp.org/nepal' },
      ],
    },
    {
      _id: 'police-officer',
      title: 'Police Officer',
      description: 'Maintain law and order, protect citizens, and enforce the law. Serve and protect the nation.',
      category: 'Security',
      icon: '👮',
      roadmap: [
        'Complete +2 in any stream',
        'Clear Nepal Police entrance exam',
        'Complete Police Training (6 months)',
        'Serve as Police Constable/Sub-Inspector',
        'Clear departmental exams for promotion',
        'Rise through ranks to DSP, SP, SSP',
      ],
      duration: 'Training: 6 months',
      cost: 'No cost (government service)',
      averageSalary: 'NPR 30,000 – 100,000/month',
      jobProspects: 'Good',
      achievements: [
        'Maintain law and order',
        'Investigate crimes and maintain records',
        'Protect citizens and communities',
        'Rise to senior police ranks',
        'Specialize in CID, SWAT, or traffic',
      ],
      benefits: [
        'Government job security',
        'Pension and benefits',
        'Serve the nation',
        'Clear promotion path',
        'Respect and honor',
      ],
      institutes: [
        { name: 'Nepal Police Academy', url: 'https://nepalpolice.gov.np' },
        { name: 'Ministry of Home Affairs', url: 'https://moha.gov.np' },
        { name: 'Nepal Police Headquarters', url: 'https://nepalpolice.gov.np' },
      ],
      resources: [
        { name: 'Nepal Police', url: 'https://nepalpolice.gov.np' },
        { name: 'Government Jobs Portal', url: 'https://www.htp://rajneeti.cdn.gov.np' },
      ],
    },
    {
      _id: 'actuary',
      title: 'Actuary',
      description: 'Analyze financial risks using mathematics and statistics. Work in insurance, finance, and consulting.',
      category: 'Finance',
      icon: '📈',
      roadmap: [
        'Complete +2 in Science with Math',
        'Earn Bachelor in Math, Statistics, or Actuarial Science',
        'Clear actuarial exams (SOA, CAS, or IAI)',
        'Gain experience in insurance or finance',
        'Complete all actuarial exams',
        'Specialize in life, health, or pension',
      ],
      duration: '4–8 years (exams)',
      cost: 'NPR 300,000 – 1,000,000',
      averageSalary: 'NPR 80,000 – 300,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Price insurance products accurately',
        'Assess and manage financial risks',
        'Work as Chief Actuary or Risk Manager',
        'Consult for insurance companies',
        'Set financial strategy for organizations',
      ],
      benefits: [
        'One of the highest-paying professions',
        'In-demand globally',
        'Intellectually challenging',
        'Work in prestigious firms',
        'Excellent job security',
      ],
      institutes: [
        { name: 'Tribhuvan University (Math/Stats)', url: 'https://tu.edu.np' },
        { name: 'SOA (Society of Actuaries)', url: 'https://www.soa.org' },
        { name: 'CAS (Casualty Actuarial Society)', url: 'https://www.casact.org' },
        { name: 'IAI (India)', url: 'https://www.actuariesindia.org' },
      ],
      resources: [
        { name: 'Society of Actuaries', url: 'https://www.soa.org' },
        { name: 'Actuarial Outpost', url: 'https://www.actuarialoutpost.com' },
      ],
    },
    {
      _id: 'physiotherapist',
      title: 'Physiotherapist',
      description: 'Help people recover from injuries and improve physical function. Essential for rehabilitation and sports.',
      category: 'Healthcare',
      icon: '💪',
      roadmap: [
        'Complete +2 Science with Biology',
        'Join BPT (Bachelor of Physiotherapy) program',
        'Complete 4.5-year physiotherapy degree',
        'Gain clinical experience through internships',
        'Register with Nepal Health Professional Council',
        'Specialize in sports, neurology, or orthopedics',
      ],
      duration: '4.5 years',
      cost: 'NPR 500,000 – 2,000,000',
      averageSalary: 'NPR 30,000 – 80,000/month',
      jobProspects: 'Good',
      achievements: [
        'Rehabilitate patients from injuries',
        'Work with sports teams or hospitals',
        'Specialize in specific conditions',
        'Open your own physiotherapy clinic',
        'Teach or research physiotherapy',
      ],
      benefits: [
        'Growing healthcare field',
        'Direct impact on patient recovery',
        'Work in various settings',
        'Entrepreneurship opportunities',
        'Demand in sports and elderly care',
      ],
      institutes: [
        { name: 'Kathmandu University (Medical)', url: 'https://ku.edu.np' },
        { name: 'B.P. Koirala Institute', url: 'https://bpkohs.edu.np' },
        { name: 'Pokhara University', url: 'https://pu.edu.np' },
        { name: 'Online: APTA', url: 'https://www.apta.org' },
      ],
      resources: [
        { name: 'American Physical Therapy Association', url: 'https://www.apta.org' },
        { name: 'World Confederation for PT', url: 'https://www.wcpt.org' },
      ],
    },
    {
      _id: 'content-creator',
      title: 'Content Creator / YouTuber',
      description: 'Create videos, blogs, and social media content. Build an audience and monetize your creativity.',
      category: 'Media',
      icon: '🎥',
      roadmap: [
        'Identify your niche (education, entertainment, vlogs)',
        'Learn video editing and content creation',
        'Start uploading consistently on YouTube/Social Media',
        'Build an audience and engagement',
        'Monetize through ads, sponsors, and products',
        'Scale to full-time content creation',
      ],
      duration: '1–2 years to full-time',
      cost: 'NPR 20,000 – 200,000 (equipment)',
      averageSalary: 'NPR 0 – 500,000/month (varies)',
      jobProspects: 'Good',
      achievements: [
        'Build a loyal audience',
        'Earn through ad revenue and sponsorships',
        'Create your own brand',
        'Work with brands and companies',
        'Influence and inspire others',
      ],
      benefits: [
        'Be your own boss',
        'Creative freedom',
        'Potential for high income',
        'Work from anywhere',
        'Build personal brand',
      ],
      institutes: [
        { name: 'Online: YouTube Creator Academy', url: 'https://www.youtube.com/creator/academy' },
        { name: 'Skillshare', url: 'https://www.skillshare.com' },
        { name: 'Coursera Content Creation', url: 'https://www.coursera.org' },
      ],
      resources: [
        { name: 'YouTube Creators', url: 'https://www.youtube.com/creators' },
        { name: 'TubeBuddy', url: 'https://www.tubebuddy.com' },
      ],
    },
    {
      _id: 'real-estate',
      title: 'Real Estate Agent',
      description: 'Help people buy, sell, and rent properties. Nepal\'s real estate market is growing rapidly.',
      category: 'Business',
      icon: '🏠',
      roadmap: [
        'Complete +2 in any stream',
        'Register with Nepal Real Estate Commission',
        'Complete real estate licensing process',
        'Join a real estate agency',
        'Build network and client base',
        'Start your own real estate business',
      ],
      duration: 'Training: 1–3 months',
      cost: 'NPR 10,000 – 50,000',
      averageSalary: 'NPR 30,000 – 200,000/month',
      jobProspects: 'Good',
      achievements: [
        'Help families find their dream homes',
        'Close high-value property deals',
        'Build extensive property network',
        'Earn commission on sales',
        'Become top real estate broker',
      ],
      benefits: [
        'Unlimited earning potential',
        'Flexible work schedule',
        'Growing market in Nepal',
        'Build valuable network',
        'Entrepreneurship opportunities',
      ],
      institutes: [
        { name: 'Nepal Real Estate Commission', url: 'https://nrec.gov.np' },
        { name: 'Nepal Association of Realtors', url: 'https://www.nar.org' },
        { name: 'Online: NAR Global', url: 'https://www.nar.org' },
      ],
      resources: [
        { name: 'Nepal Real Estate Commission', url: 'https://nrec.gov.np' },
        { name: 'Property Sites Nepal', url: 'https://www.propertynepal.com' },
      ],
    },
  ]);

  await Skill.insertMany([
    {
      _id: 'web-development',
      name: 'Web Development',
      description: 'Build full-stack web applications from scratch. Master both frontend and backend technologies to become a complete developer.',
      category: 'Technology',
      level: 'Intermediate',
      steps: [
        'Learn HTML, CSS, and JavaScript fundamentals',
        'Master React.js for frontend development',
        'Learn Node.js and Express for backend',
        'Work with MongoDB databases',
        'Build and deploy full-stack projects',
        'Create a professional portfolio with 3+ projects',
      ],
      resources: [
        { name: 'freeCodeCamp', url: 'https://freecodecamp.org' },
        { name: 'The Odin Project', url: 'https://theodinproject.com' },
        { name: 'MDN Web Docs', url: 'https://developer.mozilla.org' },
      ],
      duration: '6–9 months',
      price: 'NPR 30,000 – 150,000 (self-study to bootcamp)',
      averageSalary: 'NPR 50,000 – 120,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Build dynamic web applications from scratch',
        'Work as a full-stack developer in startups or corporates',
        'Freelance for international clients earning in USD',
        'Launch your own SaaS product or web agency',
      ],
      benefits: [
        'High demand in Nepal and globally',
        'Work remotely from anywhere',
        'Continuous learning with new frameworks',
        'Strong community support and resources',
        'Clear path to senior roles and high salaries',
      ],
      institutes: [
        { name: 'Leapfrog Technology Academy', url: 'https://www.lftechnology.com' },
        { name: 'Broadway Infosys', url: 'https://www.broadwayinfosys.com' },
        { name: 'TechAxis', url: 'https://www.techaxis.com.np' },
        { name: 'Online: Coursera Web Development', url: 'https://www.coursera.org' },
      ],
    },
    {
      _id: 'data-science',
      name: 'Data Science & AI',
      description: 'Analyze complex data and build machine learning models to drive business decisions. One of the fastest growing fields globally.',
      category: 'Technology',
      level: 'Intermediate',
      steps: [
        'Master Python programming and statistics fundamentals',
        'Learn SQL for database querying',
        'Study data analysis with Pandas and NumPy',
        'Build machine learning models with Scikit-learn',
        'Visualize data with Tableau or Power BI',
        'Work on real Nepal-based datasets',
      ],
      resources: [
        { name: 'Kaggle Learn', url: 'https://kaggle.com/learn' },
        { name: 'fast.ai', url: 'https://fast.ai' },
        { name: 'Google Data Analytics Certificate', url: 'https://grow.google/certificates/data-analytics/' },
      ],
      duration: '4–8 months',
      price: 'NPR 40,000 – 200,000',
      averageSalary: 'NPR 60,000 – 150,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Analyze large datasets to extract business insights',
        'Build predictive models for real-world problems',
        'Work as Data Analyst, Data Scientist, or ML Engineer',
        'Create AI solutions for local Nepal markets',
      ],
      benefits: [
        'One of the highest-paying tech fields',
        'Growing demand across all industries',
        'Work on impactful, data-driven projects',
        'Options to work remotely for global companies',
        'Strong future growth potential with AI',
      ],
      institutes: [
        { name: 'DataCamp', url: 'https://www.datacamp.com' },
        { name: 'Coursera Data Science Specialization', url: 'https://www.coursera.org' },
        { name: 'Scaler Academy', url: 'https://www.scaler.com' },
        { name: 'Online: Udemy Data Science', url: 'https://www.udemy.com' },
      ],
    },
    {
      _id: 'digital-marketing',
      name: 'Digital Marketing',
      description: 'Master online marketing strategies including SEO, social media, Google Ads, and content marketing to grow brands.',
      category: 'Business',
      level: 'Beginner',
      steps: [
        'Learn the fundamentals of digital marketing',
        'Master SEO basics and on-page optimization',
        'Study Google Ads and PPC campaigns',
        'Learn social media marketing strategies',
        'Practice with real Nepali business projects',
        'Build a portfolio with case studies',
      ],
      resources: [
        { name: 'Google Digital Garage', url: 'https://learndigital.withgoogle.com' },
        { name: 'HubSpot Academy', url: 'https://academy.hubspot.com' },
        { name: 'Meta Blueprint', url: 'https://www.facebook.com/business/learn' },
      ],
      duration: '3–6 months',
      price: 'NPR 15,000 – 80,000',
      averageSalary: 'NPR 30,000 – 70,000/month',
      jobProspects: 'Good',
      achievements: [
        'Manage digital marketing campaigns for brands',
        'Increase website traffic and conversions',
        'Work as Digital Marketing Manager or SEO Specialist',
        'Start your own digital marketing agency',
        'Freelance for international clients',
      ],
      benefits: [
        'High demand as every business needs online presence',
        'Can start with minimal investment',
        'Work remotely and flexibly',
        'Clear metrics to measure success',
        'Multiple specialization paths (SEO, PPC, Social)',
      ],
      institutes: [
        { name: 'Google Digital Garage', url: 'https://learndigital.withgoogle.com' },
        { name: 'HubSpot Academy', url: 'https://academy.hubspot.com' },
        { name: 'Digital Nepal Academy', url: 'https://www.digitalnepal.com' },
        { name: 'Online: Coursera Digital Marketing', url: 'https://www.coursera.org' },
      ],
    },
    {
      _id: 'ui-ux-design',
      name: 'UI/UX Design',
      description: 'Design intuitive and beautiful digital products. Bridge the gap between users and technology through user-centered design.',
      category: 'Design',
      level: 'Beginner',
      steps: [
        'Learn design principles (typography, color, layout)',
        'Master Figma or Adobe XD',
        'Study user research and personas',
        'Create wireframes and prototypes',
        'Build a portfolio with 3+ case studies',
        'Practice with real Nepal-based projects',
      ],
      resources: [
        { name: 'Google UX Design Certificate', url: 'https://grow.google/certificates/ux-design/' },
        { name: 'Figma Learn', url: 'https://figma.com/resources/learn-design/' },
        { name: 'Interaction Design Foundation', url: 'https://www.interaction-design.org' },
      ],
      duration: '3–6 months',
      price: 'NPR 20,000 – 100,000',
      averageSalary: 'NPR 40,000 – 100,000/month',
      jobProspects: 'Very Good',
      achievements: [
        'Design user-friendly mobile apps and websites',
        'Conduct user research and usability testing',
        'Work as UI/UX Designer in tech companies',
        'Create impactful design systems',
        'Freelance for international clients',
      ],
      benefits: [
        'Creative work with tangible outcomes',
        'High demand in tech startups',
        'Work collaboratively with developers',
        'Multiple industries to work in',
        'Strong community and design resources',
      ],
      institutes: [
        { name: 'Google UX Design Certificate', url: 'https://grow.google/certificates/ux-design/' },
        { name: 'Interaction Design Foundation', url: 'https://www.interaction-design.org' },
        { name: 'Shillong SGS Institute', url: 'https://www.sgsits.ac.in' },
        { name: 'Online: Udemy UI/UX Design', url: 'https://www.udemy.com' },
      ],
    },
    {
      _id: 'python-programming',
      name: 'Python Programming',
      description: 'Start your coding journey with the world\'s most versatile and beginner-friendly programming language.',
      category: 'Programming',
      level: 'Beginner',
      steps: [
        'Install Python and set up development environment',
        'Learn variables, data types, and operators',
        'Master loops, conditions, and functions',
        'Understand object-oriented programming',
        'Explore libraries: NumPy, Pandas, Flask/Django',
        'Build small projects and automate tasks',
      ],
      resources: [
        { name: 'Python.org Docs', url: 'https://docs.python.org' },
        { name: 'Automate the Boring Stuff', url: 'https://automatetheboringstuff.com' },
        { name: 'Codecademy Python', url: 'https://www.codecademy.com' },
      ],
      duration: '3–6 months',
      price: 'NPR 10,000 – 60,000 (self-study to courses)',
      averageSalary: 'NPR 40,000 – 100,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Automate repetitive tasks and save hours of work',
        'Build data analysis and visualization tools',
        'Develop web applications with Flask/Django',
        'Start a career in AI/ML or backend development',
      ],
      benefits: [
        'Easy to learn for beginners',
        'Used in web, AI, data science, automation',
        'Large community and extensive libraries',
        'High-paying and in-demand globally',
        'Foundation for advanced programming careers',
      ],
      institutes: [
        { name: 'Broadway Infosys', url: 'https://www.broadwayinfosys.com' },
        { name: 'Online: Coursera Python', url: 'https://www.coursera.org' },
        { name: 'Online: Codecademy', url: 'https://www.codecademy.com' },
        { name: 'Scaler Academy', url: 'https://www.scaler.com' },
      ],
    },
    {
      _id: 'mobile-app-development',
      name: 'Mobile App Development',
      description: 'Build iOS and Android applications using Flutter or React Native. Mobile development is booming in Nepal\'s fintech and e-commerce sectors.',
      category: 'Technology',
      level: 'Intermediate',
      steps: [
        'Choose Flutter or React Native',
        'Learn the framework fundamentals',
        'Build UI components and navigation',
        'Work with APIs and backend integration',
        'Test and debug your applications',
        'Publish to App Store and Play Store',
      ],
      resources: [
        { name: 'Flutter Docs', url: 'https://docs.flutter.dev' },
        { name: 'React Native Docs', url: 'https://reactnative.dev' },
        { name: 'Flutter YouTube Tutorials', url: 'https://www.youtube.com/c/Flutter' },
      ],
      duration: '4–7 months',
      price: 'NPR 30,000 – 120,000',
      averageSalary: 'NPR 50,000 – 130,000/month',
      jobProspects: 'Excellent',
      achievements: [
        'Build and publish apps to Play Store and App Store',
        'Work as Mobile Developer in startups',
        'Develop fintech or e-commerce apps for Nepal market',
        'Create your own mobile app startup',
      ],
      benefits: [
        'High demand as mobile usage grows',
        'Work on products used by millions',
        'Excellent salary potential',
        'Creative and challenging work',
        'Multiple platforms to build for',
      ],
      institutes: [
        { name: 'Leapfrog Technology Academy', url: 'https://www.lftechnology.com' },
        { name: 'TechAxis', url: 'https://www.techaxis.com.np' },
        { name: 'Online: Flutter Complete Course', url: 'https://www.udemy.com' },
        { name: 'Online: React Native Course', url: 'https://www.coursera.org' },
      ],
    },
    {
      _id: 'graphic-design',
      name: 'Graphic Design',
      description: 'Create stunning visual content for brands, social media, and print. Turn your creativity into a career.',
      category: 'Design',
      level: 'Beginner',
      steps: [
        'Learn design principles and color theory',
        'Master Canva or Adobe Illustrator basics',
        'Study typography and layout design',
        'Create social media content and posters',
        'Build a portfolio on Behance or Dribbble',
        'Start freelancing on Fiverr or Upwork',
      ],
      resources: [
        { name: 'Canva Design School', url: 'https://www.canva.com/design-school' },
        { name: 'Adobe Learn', url: 'https://helpx.adobe.com/illustrator/tutorials.html' },
        { name: 'Dribbble Learn', url: 'https://dribbble.com/learn' },
      ],
      duration: '2–4 months',
      price: 'NPR 10,000 – 50,000',
      averageSalary: 'NPR 25,000 – 60,000/month',
      jobProspects: 'Good',
      achievements: [
        'Create professional brand identities',
        'Design social media content for businesses',
        'Work as in-house designer or freelancer',
        'Start your own design agency',
        'Build international client base',
      ],
      benefits: [
        'Creative and fulfilling work',
        'Can start with free tools like Canva',
        'High demand for quality design',
        'Flexible work and freelance opportunities',
        'Build portfolio while learning',
      ],
      institutes: [
        { name: 'Arena Animation', url: 'https://www.arena-multimedia.com' },
        { name: 'Pixator Academy', url: 'https://www.pixator.com' },
        { name: 'Online: Canva Design School', url: 'https://www.canva.com/design-school' },
        { name: 'Online: Adobe Tutorials', url: 'https://helpx.adobe.com' },
      ],
    },
    {
      _id: 'english-proficiency',
      name: 'English Proficiency',
      description: 'Achieve your target IELTS/PTE score for abroad studies and improve professional English communication.',
      category: 'Language',
      level: 'Beginner',
      steps: [
        'Assess your current English level',
        'Build vocabulary with daily practice',
        'Master IELTS/PTE test format and strategies',
        'Practice speaking with language partners',
        'Take regular mock tests',
        'Focus on weak areas identified in tests',
      ],
      resources: [
        { name: 'British Council Nepal', url: 'https://www.britishcouncil.org.np' },
        { name: 'IELTS Liz', url: 'https://ieltsliz.com' },
        { name: 'PTE Academic Official', url: 'https://www.pearson.com/pte' },
      ],
      duration: '2–4 months',
      price: 'NPR 15,000 – 50,000',
      averageSalary: 'NPR 40,000 – 80,000/month (teaching)',
      jobProspects: 'Good',
      achievements: [
        'Achieve IELTS 6.5+ or PTE 60+ score',
        'Qualify for study abroad programs',
        'Improve job interview performance',
        'Work as English tutor or trainer',
        'Communicate confidently in professional settings',
      ],
      benefits: [
        'Essential for studying abroad',
        'Improves career opportunities',
        'Better communication in tech industry',
        'Opens doors to international work',
        'Confidence in presentations and meetings',
      ],
      institutes: [
        { name: 'British Council Nepal', url: 'https://www.britishcouncil.org.np' },
        { name: 'IDP IELTS Nepal', url: 'https://www.idp.com/nepal' },
        { name: 'British American Resource Center', url: 'https://www.barc.edu.np' },
        { name: 'Online: IELTS Liz', url: 'https://ieltsliz.com' },
      ],
    },
    {
      _id: 'financial-accounting',
      name: 'Financial Accounting',
      description: 'Master accounting principles, Tally ERP, and financial management. Essential for CA aspirants and business professionals.',
      category: 'Business',
      level: 'Beginner',
      steps: [
        'Learn basic accounting concepts and principles',
        'Master Tally ERP software',
        'Study Excel for financial calculations',
        'Understand GST and tax compliance',
        'Practice with real company ledgers',
        'Prepare financial statements and reports',
      ],
      resources: [
        { name: 'Tally Education', url: 'https://www.tallyeducation.com' },
        { name: 'ICAN (Institute of Chartered Accountants of Nepal)', url: 'https://www.ican.org.np' },
        { name: 'Microsoft Excel Training', url: 'https://support.microsoft.com/en-us/excel' },
      ],
      duration: '3–6 months',
      price: 'NPR 15,000 – 60,000',
      averageSalary: 'NPR 30,000 – 80,000/month',
      jobProspects: 'Very Good',
      achievements: [
        'Maintain complete accounting records for businesses',
        'Prepare tax returns and compliance documents',
        'Work as Accountant or Finance Executive',
        'Start your path towards CA qualification',
        'Manage finances for SMEs or startups',
      ],
      benefits: [
        'High demand in every organization',
        'Essential skill for running a business',
        'Clear career progression path',
        'Foundation for CA/CPA qualification',
        'Work in any industry',
      ],
      institutes: [
        { name: 'ICAN (Institute of Chartered Accountants of Nepal)', url: 'https://www.ican.org.np' },
        { name: 'Tally Training Centers', url: 'https://www.tallyeducation.com' },
        { name: 'Shri Ram College of Commerce (India)', url: 'https://www.srcc.du.ac.in' },
        { name: 'Online: Accounting Coach', url: 'https://www.accountingcoach.com' },
      ],
    },
  ]);

  await Article.insertMany([
    {
      title: 'Top 10 In-Demand Careers in Nepal for 2025',
      excerpt: 'Nepal\'s job market is evolving rapidly. Here are the careers with the highest growth potential.',
      content: 'Nepal\'s economy is transforming. IT, healthcare, engineering, and entrepreneurship are leading the way. Here are the top careers to watch in 2025...',
      category: 'Career Advice',
      author: 'NextStep Team',
      readTime: '5 min',
      date: new Date('2025-01-15'),
    },
    {
      title: 'How to Study Abroad from Nepal: A Complete Guide',
      excerpt: 'Everything you need to know about scholarships, visa, and choosing the right country.',
      content: 'Studying abroad can transform your career. From IELTS preparation to finding scholarships, this guide covers everything...',
      category: 'Study Abroad',
      author: 'Priya Sharma',
      readTime: '8 min',
      date: new Date('2025-02-01'),
    },
    {
      title: 'Freelancing in Nepal: Turn Your Skills Into Income',
      excerpt: 'Thousands of Nepali youth are earning in USD from home. Here\'s how to start.',
      content: 'The gig economy is booming. Platforms like Upwork, Fiverr, and Toptal offer Nepali freelancers access to global clients...',
      category: 'Entrepreneurship',
      author: 'Rohan KC',
      readTime: '6 min',
      date: new Date('2025-02-20'),
    },
    {
      title: 'IOE vs TU vs Kathmandu University: Which is Right for You?',
      excerpt: 'A detailed comparison of Nepal\'s top universities to help you make the right choice.',
      content: 'Choosing the right university is one of the most important decisions. Let\'s compare the top options...',
      category: 'Study Nepal',
      author: 'NextStep Team',
      readTime: '7 min',
      date: new Date('2025-03-01'),
    },
    {
      title: 'IELTS vs TOEFL: Which Exam Should Nepali Students Take?',
      excerpt: 'Breaking down the differences and helping you choose the right English proficiency test.',
      content: 'If you plan to study abroad, you\'ll need to prove your English. Here\'s the definitive comparison...',
      category: 'Study Abroad',
      author: 'Anjali Thapa',
      readTime: '4 min',
      date: new Date('2025-03-10'),
    },
  ]);

  console.log('✅ Database seeded successfully!');
}